# Template

name: "My action"
description: "Test my action"

inputs:
  message:
    description: "The message to print"
    required: true
    default: "Mundo"

runs:
  using: "composite"

  steps:
    - name: Hola Mundo
      run: echo "Hello, ${{ inputs.message }}!"
      shell: bash

    - name: run script
      run: |
        chmod +x script.sh
        ./script.sh
      shell: bash
