# Template

name: "My action"
description: "Test my action"

runs:
  using: "composite"

  steps:
    - name: Hola Mundo
      run: echo "Hello, World!"
      shell: bash

    - name: run script
      run: |
        chmod +x script.sh
        ./script.sh
      shell: bash
